### PR TITLE
add security http headers

### PR DESCRIPTION
**Pull request by alismed**
## Description

I added a few http headers related to information security.
To test:
 1. I exposed my localhost using https://serveo.net/
 2. Using a service like https://securityheaders.com/, I tested the new url created.

### CODE REVIEW

**Comment by alismed** [comment]
> Hi, @alismed, first, thanks for contributing!
> 
> I have 2 questions.
> 
> 1. Why do we need this setting in the local environment?
> 2. What do you think of doing this setup for a production environment?

I agree in local environment isn't necessary. I used the local environment only to test.  I didn't realise that are separated environment.

**Comment by mvfsillva** [comment]
You could set the config for production environment?

**Comment by alismed** [comment]
> You could set the config for production environment?

Yes. In fact, I am not sure how, but I will learn. kkk
You should reject this pr. I will create a new one.

**Comment by mvfsillva** [comment]
Ok @alismed, thanks, I await its pull request!

**Pull request closed without merging**
